version: "3.9"  # version "3" is obsolete, update to 3.9

services:
  application:
    image: spring-boot-mysql-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - ./src:/app/src  # adjust path to match your project
    develop:
      watch:
        - action: rebuild
          path: ./src

  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    volumes:
      - /home/rohit/app:/var/lib/mysql

networks:
  springboot-db-net:
